# Generated by Django 2.0.3 on 2018-04-20 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='stockentry',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='stockentry',
            name='updated_at',
        ),
    ]
